---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: text
  name: year
  label: year
- type: file
  name: thumbnail
  label: thumbnail
- type: boolean
  name: thumbnail_video
  label: thumbnail_video
- type: list
  name: categories
  label: categories
